import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { Layers, Cpu, CheckCircle, Database } from "lucide-react";
import { toast } from "sonner";
import { Metric, Panel, Pill } from "@/components/aeon/primitives";

export const Route = createFileRoute("/advisor")({
  head: () => ({
    meta: [
      { title: "Schema & MCP Advisor | Aeon" },
      {
        name: "description",
        content:
          "AI sub-agent schema and index advisor analysing CockroachDB performance through the managed MCP server at cockroachlabs.cloud/mcp.",
      },
      { property: "og:title", content: "Schema & MCP Advisor | Aeon" },
      {
        property: "og:description",
        content:
          "One-click SQL recommendations generated by Aeon's schema advisor sub-agent over CockroachDB MCP telemetry.",
      },
    ],
  }),
  component: AdvisorView,
});

const RECOMMENDATIONS = [
  {
    id: "rec-01",
    title: "Recommend creating secondary VECTOR INDEX on runbook_embeddings",
    impact: "Est. −68% vector search latency",
    tone: "info" as const,
    sql: "CREATE VECTOR INDEX runbook_embeddings_cosine_idx\n  ON runbook_embeddings (embedding vector_cosine_ops);",
  },
  {
    id: "rec-02",
    title: "Add covering index on agent_execution_sessions (session_id, step_no)",
    impact: "Est. −41% checkpoint read amplification",
    tone: "success" as const,
    sql: "CREATE INDEX sessions_step_idx\n  ON agent_execution_sessions (session_id, step_no)\n  STORING (context_state, last_persisted_step);",
  },
  {
    id: "rec-03",
    title: "Pin incident_audit_log to REGIONAL BY ROW for locality reads",
    impact: "Est. −29 ms eu-central-1 p99",
    tone: "warning" as const,
    sql: "ALTER TABLE incident_audit_log SET LOCALITY REGIONAL BY ROW;",
  },
];

function AdvisorView() {
  const [applied, setApplied] = useState<string[]>([]);

  const apply = (id: string, title: string) => {
    setApplied((a) => [...a, id]);
    toast.success("SQL applied via MCP", { description: title });
  };

  return (
    <div className="space-y-5">
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <Metric label="MCP endpoint" value="Connected" hint="cockroachlabs.cloud/mcp" tone="success" />
        <Metric label="Statements analysed" value="24,819" hint="last 6 hours" tone="info" />
        <Metric label="Open recommendations" value={`${RECOMMENDATIONS.length - applied.length}`} />
        <Metric label="Applied this week" value={`${7 + applied.length}`} tone="success" />
      </div>

      <Panel
        title="Schema Advisor Sub-Agent"
        subtitle="Reasoning over MCP query telemetry with Claude 3.5 Sonnet"
        icon={<Cpu className="size-4" />}
        action={<Pill tone="success" pulse>Analysing</Pill>}
      >
        <div className="space-y-3">
          {RECOMMENDATIONS.map((r) => {
            const done = applied.includes(r.id);
            return (
              <article
                key={r.id}
                className="animate-fade-up rounded-xl bg-card p-4 ring-1 ring-border-subtle"
              >
                <div className="grid grid-cols-[minmax(0,1fr)_auto] items-start gap-3">
                  <div className="min-w-0">
                    <p className="text-sm font-semibold">{r.title}</p>
                    <p className="mt-1 text-xs text-muted-foreground">{r.impact}</p>
                  </div>
                  <Pill tone={done ? "success" : r.tone}>
                    {done ? (
                      <>
                        <CheckCircle className="size-3" /> Applied
                      </>
                    ) : (
                      "Pending"
                    )}
                  </Pill>
                </div>
                <pre className="mt-3 overflow-x-auto rounded-lg bg-surface p-3 font-mono text-[0.7rem] leading-relaxed text-foreground/90 ring-1 ring-border-subtle">
                  {r.sql}
                </pre>
                <div className="mt-3 flex justify-end">
                  <button
                    disabled={done}
                    onClick={() => apply(r.id, r.title)}
                    className="inline-flex items-center gap-2 rounded-xl bg-primary px-3.5 py-2 text-xs font-semibold text-primary-foreground transition-transform hover:scale-[1.02] disabled:opacity-40 disabled:hover:scale-100"
                  >
                    <Database className="size-3.5" />
                    {done ? "Applied via MCP" : "Apply SQL"}
                  </button>
                </div>
              </article>
            );
          })}
        </div>
      </Panel>

      <Panel
        title="MCP Session Inspector"
        subtitle="Managed CockroachDB MCP server"
        icon={<Layers className="size-4" />}
        bodyClassName="p-0"
      >
        <div className="divide-y divide-border-subtle font-mono text-xs">
          {[
            ["tools/list", "8 tools · sql.query, cluster.metrics, audit.read"],
            ["sql.query", "SHOW STATEMENT STATISTICS → 24,819 rows"],
            ["cluster.metrics", "3 nodes healthy · cpu 0.34 avg"],
            ["audit.read", "no transactional errors in window"],
          ].map(([m, d]) => (
            <div key={m} className="grid gap-1 px-5 py-3 sm:grid-cols-[12rem_minmax(0,1fr)]">
              <span className="text-info">{m}</span>
              <span className="min-w-0 break-words text-muted-foreground">{d}</span>
            </div>
          ))}
        </div>
      </Panel>
    </div>
  );
}
