/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdvisorRouteImport } from './routes/advisor'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as TelemetryRouteImport } from './routes/telemetry'
import { Route as TopologyRouteImport } from './routes/topology'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorRoute = AdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const TelemetryRoute = TelemetryRouteImport.update({
  id: '/telemetry',
  path: '/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const TopologyRoute = TopologyRouteImport.update({
  id: '/topology',
  path: '/topology',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/audit': typeof AuditRoute
  '/memory': typeof MemoryRoute
  '/telemetry': typeof TelemetryRoute
  '/topology': typeof TopologyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/audit': typeof AuditRoute
  '/memory': typeof MemoryRoute
  '/telemetry': typeof TelemetryRoute
  '/topology': typeof TopologyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/audit': typeof AuditRoute
  '/memory': typeof MemoryRoute
  '/telemetry': typeof TelemetryRoute
  '/topology': typeof TopologyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/advisor' | '/audit' | '/memory' | '/telemetry' | '/topology'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/advisor' | '/audit' | '/memory' | '/telemetry' | '/topology'
  id:
    | '__root__'
    | '/'
    | '/advisor'
    | '/audit'
    | '/memory'
    | '/telemetry'
    | '/topology'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvisorRoute: typeof AdvisorRoute
  AuditRoute: typeof AuditRoute
  MemoryRoute: typeof MemoryRoute
  TelemetryRoute: typeof TelemetryRoute
  TopologyRoute: typeof TopologyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor': {
      id: '/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telemetry': {
      id: '/telemetry'
      path: '/telemetry'
      fullPath: '/telemetry'
      preLoaderRoute: typeof TelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topology': {
      id: '/topology'
      path: '/topology'
      fullPath: '/topology'
      preLoaderRoute: typeof TopologyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvisorRoute: AdvisorRoute,
  AuditRoute: AuditRoute,
  MemoryRoute: MemoryRoute,
  TelemetryRoute: TelemetryRoute,
  TopologyRoute: TopologyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
